version: '3.4'

services:
    weather:
        image: pica/weather:2.0.0
        build:
            context: .
        ports:
            - "8070:8080"
        networks:
            - springboot

networks:
    springboot:
